title: Cloud & DevOps resources
author: JPL
email: jpl@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Cloud & DevOps resources for learning... 
theme: minima
# social links
twitter_username: jpl # DO NOT include the @ character, or else the build will fail!
github_username:  JustPLegend # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
